apiVersion: v1
kind: Service
metadata:
  name: billing-app
spec:
  clusterIP: None
  selector:
    app: billing-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app
spec:
  serviceName: billing-app
  replicas: 1
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      containers:
        - name: billing-app
          image: aymening01/billing-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: BILLING_DB_HOST
              value: "billing-db"

            - name: BILLING_DB_PORT
              value: "5432"

            - name: BILLING_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: BILLING_DB_USER
            - name: BILLING_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: BILLING_DB_PASSWORD
            - name: BILLING_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: BILLING_DB_NAME
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: RABBITMQ_USER

            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_QUEUE
              value: "billing_queue"
          envFrom:
            - configMapRef:
                name: app-config
