apiVersion: v1
kind: Service
metadata:
  name: billing-db
spec:
  clusterIP: None
  selector:
    app: billing-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-db
spec:
  serviceName: billing-db
  replicas: 1
  selector:
    matchLabels:
      app: billing-db
  template:
    metadata:
      labels:
        app: billing-db
    spec:
      containers:
        - name: billing-db
          image: aymening01/billing-db:v1.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: orchestrator-secrets
                  key: BILLING_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orchestrator-secrets
                  key: BILLING_DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: orchestrator-config
                  key: BILLING_DB_NAME
          volumeMounts:
            - name: billing-db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: billing-db-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi
