apiVersion: v1
kind: Service
metadata:
  name: inventory-app
spec:
  selector:
    app: inventory-app
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
        - name: inventory-app
          image: aymening01/inventory-app:latest
          ports:
            - containerPort: 8080

          env:
            - name: INVENTORY_DB_HOST
              value: inventory-db.default.svc.cluster.local

            - name: INVENTORY_DB_PORT
              value: "5432"

            - name: INVENTORY_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: INVENTORY_DB_NAME

            - name: INVENTORY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: INVENTORY_DB_USER

            - name: INVENTORY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: INVENTORY_DB_PASSWORD

          envFrom:
            - configMapRef:
                name: app-config

          resources:
            requests:
              cpu: 100m

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
