apiVersion: v1
kind: Secret
metadata:
  name: orchestrator-secrets
type: Opaque
stringData:
  INVENTORY_DB_USER: appuser
  INVENTORY_DB_PASSWORD: CHANGE_ME_INVENTORY_PASSWORD
  BILLING_DB_USER: appuser
  BILLING_DB_PASSWORD: CHANGE_ME_BILLING_PASSWORD
  RABBITMQ_USER: app_user
  RABBITMQ_PASSWORD: CHANGE_ME_RABBITMQ_PASSWORD
